### ISSUE TITLE
Copying line of sample code copies the dollar sign ($) along it

### ISSUE THREAD

**Issue by LL-Etiane** [wwebjs/wwebjs.dev#23]
When you copy a code sample like for installing the module, the $ sign gets copied also. Example when you copy the install command and paste in your console, what you get will be ```$ npm i whatsapp-web.js ```

**Comment by xdarkki** [comment]
Yes that was most likely added because of the typing in bash. 
Of course it shouldn't be inserted like that...

**Comment by msscsh** [comment]
The dollar sign is intended to introduce the reader to the understanding of "command start". I don't agree that it should be removed because someone messed up and copied it to the terminal. It even looks like a kind of natural filter.
