### ISSUE TITLE
Whatsapp web error

### ISSUE THREAD

**Issue by gersonnotico** [wwebjs/wwebjs.dev#52]
Aplicação rodando na porta *: 8001 . Acesse no link: http://localhost:8001
C:\chatbot_mcbc\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (C:\chatbot_mcbc\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\chatbot_mcbc\node_modules\whatsapp-web.js\src\Client.js:771:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by qzdark** [comment]
That's the wrong repository. Look for help here: https://github.com/pedroslopez/whatsapp-web.js.

**Comment by rajanchicmic** [comment]
@qzdark, the repository you mentioned having same issue. Please check

**Comment by qzdark** [comment]
@rajanchicmic, this is not the repository. The guide repository and has no effect on the library. If you have a problem, look for help or report a bug there.
