### ISSUE TITLE
error in LocalWebCache.js:34

### ISSUE THREAD

**Issue by nknnkumar** [wwebjs/wwebjs.dev#54]
![image](https://github.com/wwebjs/wwebjs.dev/assets/115708070/f7a71958-a615-487a-9308-ce68675ba2bc)

![image](https://github.com/wwebjs/wwebjs.dev/assets/115708070/01288d8c-78a4-4145-b1af-23fc6165ede4)

![image](https://github.com/wwebjs/wwebjs.dev/assets/115708070/f40df047-0d1f-46d9-93e4-f51a275c038e)

**Comment by balmacefa** [comment]
This workaround works for me.
https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-1992260938

**Comment by rajanchicmic** [comment]
Getting same issue. Is there any permanent fix for this? I tried this library 15-20 days ago and it was working fine, but now it is breaking for me as well with the same manifest file version issue. In index.html script is unable to find the version information of manifest file. 


<img width="983" alt="Screenshot 2024-04-18 at 11 37 55 AM" src="https://github.com/wwebjs/wwebjs.dev/assets/53251129/20b5bbe5-45f7-4a8c-bc7d-68a3c37abc59">

**Comment by qzdark** [comment]
That's the wrong repository. Look for help here: https://github.com/pedroslopez/whatsapp-web.js.
