### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by rajanchicmic** [wwebjs/wwebjs.dev#57]
Is there any permanent fix for this? I tried this library 15-20 days ago and it was working fine, but now it is breaking for me as well with the same manifest file version issue. In index.html script is unable to find the version information of manifest file.

<img width="983" alt="Screenshot 2024-04-18 at 11 37 55 AM" src="https://github.com/wwebjs/wwebjs.dev/assets/53251129/cbb23c5e-587a-42e0-aca5-4635cf7e8ae2">

**Comment by qzdark** [comment]
That's the wrong repository. Look for help here: https://github.com/pedroslopez/whatsapp-web.js.
