### ISSUE TITLE
whatsapp-web.js / whatss

### ISSUE THREAD

**Issue by XsafiD** [wwebjs/wwebjs.dev#67]
I have followed the tutorial correctly at every stage and I am using node v22, but after installing whatsapp-web.js and creating the main code, when I run the program it appears "TypeError: Cannot read properties of null (reading '1')", so what do I have to do? Thank You
![image](https://github.com/wwebjs/wwebjs.dev/assets/140198605/472655bc-11c6-4738-8654-b1229cdbd665)

**Comment by jjuniordev** [comment]
I'm facing the same problem here... think that whatsapp made same changes that has broken the wwebjs...

**Comment by qzdark** [comment]
The issue you are mentioning here is related to [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js). This is the repository for the guide website. If you have any issues with the mentioned library, you should open them there.
